export const RESTAURANTS ={
    SET_REASTAURANTS:'SET_REASTAURANTS',
}

export const APP_STATES={
    SHOW_LOADING:'SHOW_LOADING',
    HIDE_LOADING:'HIDE_LOADING',
}

export const AUTH={
    SHOW_AUTH_ERROR:'SHOW_AUTH_ERROR',
    HIDE_AUTH_ERROR:'HIDE_AUTH_ERROR'
}