export const cuisines = [
  { name: 'Asian' },
  { name: 'Kebab' },
  { name: 'Sushi' },
  { name: 'Pizza' },
  { name: 'Vegetarian' },
  { name: 'Burger' },
  { name: 'European' },
  { name: 'French' },
  { name: 'Georgian' },
  { name: 'Shawarma' },
  { name: 'Japanese' },
  { name: 'Italian' },
  { name: 'Dinners' },
  { name: 'Belarusian' },
  { name: 'Paste' },
  { name: 'Dessert' },
];
